export const CHARS_PER_TOKEN = 4;

export const MIN_CHUNK_TOKENS = 500;

export const MAX_CHUNK_TOKENS = 1000;

export const CHUNK_OVERLAP_TOKENS = 50;

export const MIN_CHUNK_CHARS = MIN_CHUNK_TOKENS * CHARS_PER_TOKEN;

export const MAX_CHUNK_CHARS = MAX_CHUNK_TOKENS * CHARS_PER_TOKEN;

export const CHUNK_OVERLAP_CHARS = CHUNK_OVERLAP_TOKENS * CHARS_PER_TOKEN;
